### ISSUE TITLE
Exception - Class 'core_course_category' not found

### ISSUE THREAD

**Issue by djhipps** [doiphode/moodle-local_simple_course_creator#1]
Just checking this plugin out. Get this error when clicking on the "Simple Course Creator" link. Vanillia install, was on 3.2 and the upgraded to 3.6 stable. Error still occurs. 

![simplecoursecreator](https://user-images.githubusercontent.com/6058577/70797641-cc6caf80-1d9c-11ea-9837-e1f72eb9f9aa.PNG)

**Comment by doiphode** [comment]
Updated the plugin, try installing on Vanilla 3.6 directly. The plugin is written for v3.6 onwards.
